_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.10.15
            "5": 0.18.6
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.6
            "13": windows-amd64
arch_elements:
    value: 4
batch_size:
    value: 82
epochs:
    value: 200
learning_rate:
    value: 0.4707672132882979
optimizer:
    value: RMSPROP
